src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => 'electric',
        1 => 'gaz'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $filename;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10,max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;
    
    public function __construct(){
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
    
    public function getFormattedPrice():string{

        return number_format( $this->price, 0 , '' , ' ');
    }
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType():string{
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFileName(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Property
     */
    public function setFileName(?string $filename): Property
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use App\Entity\Option;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',null,[
                'label' => 'Titre'
            ])
            ->add('description',null,[
                'label' => 'Description'
            ])
            ->add('surface',null,[
                'label' => 'Surface'
            ])
            ->add('rooms',null,[
                'label' => 'Pièce'
            ])
            ->add('bedrooms',null,[
                'label' => 'Chambre'
            ])
            ->add('floor',null,[
                'label' => 'Étage'
            ])
            ->add('price',null,[
                'label' => 'Prix'
            ])
            ->add('heat',ChoiceType::class,[
                'label' => 'Chauffage',
                'choices' => $this->getChoices()
            ])
            ->add('options',EntityType::class,[
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile',FileType::class,[
                'required' => false
            ])

            ->add('city',null,[
                'label' => 'Ville'
            ])
            ->add('adress',null,[
                'label' => 'Adresse'
            ])
            ->add('postal_code',null,[
                'label' => 'Code Postal'
            ])
            ->add('sold',null,[
                'label' => 'Vendu'
            ])
            // ->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices(){
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
            # code...
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;

class PropertyController extends AbstractController
{   
    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;
    
    # Constructeur
    public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }
   
    # Méthode 
    /**
     * @Route("/biens",name="property.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response{

        // permet de récupérer le bien qui a l'id 1 
        // $property = $this->repository->find(1);
        
        // permet de récupérer l'ensemble des biens qu'il y a dans la table -- renvoi un tableau
        // $property = $this->repository->findAll();
        
        // permet de passer en paramètre un tableau avec des critères -- ici récupérer tous les biens qui sont au 4e étage 
        // $property = $this->repository->findOneBy(['floor' => 4]);
        
        // fait appel à la méthode dans PropertyRepository pour trouver les biens qui ne sont pas vendu
        // $property = $this->repository->findAllVisible();

        // équivalent du var_dump
        //dump($property);
        
        // formulaire de recherche
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        // Pagination
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1), /*page number*/
            12 /*limit per page*/
        );

        //$properties = $this->repository->findAllVisibleQuery();
        return $this->render('property/index.html.twig',[
            'current_menu' => 'properties',
            'properties'   => $properties,
            'form' => $form->createView()
        ]);
    }

    # Méthode 
    /**
     * @Route("/biens/{slug}-{id}",name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */
    public function show(Property $property, string $slug): Response{

        if($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show',[
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ],301); 
        }
        return $this->render('property/show.html.twig',[
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }

}

templates/property/_property.html.twig
<div class="card mb-4">
	{% if property.filename %}
		<img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="" style="width:100%; height:230px; ">
	{% else %}
		<img src="{{ '/images/properties/300x250.png' | imagine_filter('thumb') }}" alt="" style="width:100%; height:230px; ">
	{% endif %}

	<div class="card-body">
		<h5 class="card-title">
			<a href="{{ path('property.show', {slug: property.slug, id: property.id }) }}">{{ property.title }}</a>
		</h5>
		<p class="card-text">
			{{ property.surface }} - m² {{ property.city }} ({{ property.postalCode }})
		</p>
		<div class="text-primary">
			{{ property.formattedPrice }} €
		</div>
	</div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Voir tous nos biens' %}
{% block body %}
    <div class="jumbotron">
        <div class="container mt-4">
            {{ form_start(form)}}
                <div class="form-row align-items-end">
                
                    <div class="col">
                        {{ form_row(form.minSurface)}}
                    </div>
                    <div class="col">
                        {{ form_row(form.maxPrice)}}
                    </div>
                    <div class="col">
                        {{ form_row(form.options)}}
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <button class="btn btn-primary">Rechercher </button>
                        </div>
                    </div>
                </div>
            {{ form_end(form)}}
        </div>
    </div>

    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>

        <div class="row">

            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="navigation">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock body %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title  property.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    {% if property.filename %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="" style="width:100%; height:230px; ">
                    {% else %}
                        <img src="{{ '/images/properties/300x250.png' | imagine_filter('medium') }}" alt="" style="width:100%; height:230px; ">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{property.title}}</h1>
                    <h2>{{property.rooms}} pièces - {{property.surface}} m²</h2>
                    <div class="text-primary">
                        {{property.formattedPrice}} €
                    </div>
                    <a href="" class="btn btn-primary">Contacter l'agence</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>
            {{property.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2> Caractèristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{property.surface}}</td>
                    </tr>
                    <tr>
                        <td>Pièce</td>
                        <td>{{property.rooms}}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{property.bedrooms}}</td>
                    </tr>
                    <tr>
                        <td>Étage</td>
                        <td>{{property.floor}}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{property.heatType}}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2> Spécificités</h2> 
                <ul class="list-group">
                    {% for option in property.options %}
                    <li class="list-group-item"> {{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}